SER-171 recording buyback transactions into a data Table
one-acre-fund/ussd-sms pull request #102
Opened 2020-08-27 10:59 UTC by Bahatiroben

As a data entry officer, I want a structured data table with transaction details, so that I can enter data in Roster and conduct analyses

All details entered by the user from SER-170 are now getting saved into a dedicated dataTable

2020-08-28 15:33 UTC, nyabongo requested changes

2020-08-28 15:33 UTC, nyabongo commented on malawi/MalawiMain.js
Could you add slack alerts for instances when these project variables are not set? it is likely a good pattern for us to follow. include `project.name` and `service.name` in the slack alert

2020-08-31 08:17 UTC, Bahatiroben commented on malawi/MalawiMain.js
> Could you add slack alerts for instances when these project variables are not set? it is likely a good pattern for us to follow. include `project.name` and `service.name` in the slack alert

sounds good.

2020-08-31 08:37 UTC, shejasabin approved these changes

2020-08-31 08:42 UTC, nyabongo approved these changes

2020-08-31 13:15 UTC, merged