Ser 2019 maize recommendation 2
one-acre-fund/ussd-sms pull request #117
Opened 2020-09-03 21:20 UTC by Bahatiroben

2020-09-07 17:10 UTC, nyabongo requested changes
Assuming this is meant to be [SER-219](https://oneacrefund.atlassian.net/browse/SER-219), the test service you provide is configured as manually triggered, shouldn't it be an automatically triggered service like https://telerivet.com/p/0c6396c9/service/SV59d10a657b3e5119/edit
i.e instead of  `When manually triggered for a contact:` shouldn't it be `When incoming or outgoing call is received or answered:`

2020-09-24 15:59 UTC, nyabongo submitted a review, later dismissed

2020-09-24 15:59 UTC, nyabongo commented on TEST-RESULTS.xml
> +<?xml version="1.0" encoding="UTF-8"?>
can we not add this back to the repo?

2020-09-24 15:59 UTC, nyabongo commented on shared/rosterApi/registerClient.js
> +var Log = require('../../logger/elk/elk-logger');
Is this file neccessary for this ticket?

2020-09-24 16:01 UTC, Bahatiroben commented on TEST-RESULTS.xml
> +<?xml version="1.0" encoding="UTF-8"?>
okay.

2020-09-24 16:06 UTC, Bahatiroben commented on shared/rosterApi/registerClient.js
> +var Log = require('../../logger/elk/elk-logger');
Ohhh might have got it from another branch while rebasing.

2020-09-25 12:01 UTC, shejasabin approved these changes
The code looks good. I did not test it though

2020-09-25 12:07 UTC, Bahatiroben commented
> The code looks good. I did not test it though

The test requires a Kenyan simcard on a real device. so it was done by @nyabongo

2020-09-25 12:24 UTC, DevFojo approved these changes
LGTM

2020-09-25 12:59 UTC, merged