added sending an sms to the client stored phone number in just in time
one-acre-fund/ussd-sms pull request #149
Opened 2020-09-23 10:36 UTC by shejasabin

2020-09-23 14:26 UTC, nyabongo requested changes

2020-09-24 14:53 UTC, shejasabin commented on CHANGELOG.md
> +
okay

2020-09-24 15:49 UTC, nyabongo approved these changes

2020-09-25 05:49 UTC, Bahatiroben approved these changes

2020-09-25 10:21 UTC, merged