Ser 227 nutrition training
one-acre-fund/ussd-sms pull request #157
Opened 2020-09-28 12:19 UTC by Bahatiroben

2020-10-05 08:27 UTC, shejasabin commented on nutrition-training/translations/index.js
> +        'en-ke': 'Reply with a or b to answer',
it looks like the options are more than a and b in the above translations

2020-10-05 09:37 UTC, Bahatiroben commented on nutrition-training/translations/index.js
> +        'en-ke': 'Reply with a or b to answer',
Ohh missed that. It was like that in the translation file, and I forgot to add another option when I copied. Just adding it.

2020-10-05 10:07 UTC, shejasabin submitted a review, later dismissed
I think you will have to deal with conflicts for option 11 on the menu though

2020-10-05 10:14 UTC, nyabongo requested changes

2020-10-05 10:14 UTC, nyabongo commented on nutrition-training/translations/index.js
> +        'en-ke': 'Actually, beans have the most iron. Ugali/Rice make you full but do not contain enough iron to prevent anemia and imrove health',
improve is misspelt here

2020-10-05 10:18 UTC, Bahatiroben commented on nutrition-training/translations/index.js
> +        'en-ke': 'Actually, beans have the most iron. Ugali/Rice make you full but do not contain enough iron to prevent anemia and imrove health',
> improve is misspelt here

updated.

2020-10-19 08:01 UTC, DevFojo submitted a review, later dismissed

2020-10-20 07:52 UTC, nyabongo reviewed
Since this does not actually send the 2 way sms I think it is incomplete to be in testing. can you target this branch with the PR that completes it, then we can merge this branch into develop after the next branch is merged into this one.

2020-10-20 09:43 UTC, Bahatiroben commented
> Since this does not actually send the 2 way sms I think it is incomplete to be in testing. can you target this branch with the PR that completes it, then we can merge this branch into develop after the next branch is merged into this one.

Ok sounds good. done.

2020-10-20 10:58 UTC, nyabongo requested changes

2020-10-20 10:58 UTC, nyabongo commented on nutrition-training/translations/index.js
> +        'en-ke': '(1/6)Today we will learn about blanaced diets. Eating like this prevents anemia and improves the energy and health of the whole family!',
typo in "... learn about **blanaced** diets"

2020-10-20 11:05 UTC, Bahatiroben commented on nutrition-training/translations/index.js
> +        'en-ke': '(1/6)Today we will learn about blanaced diets. Eating like this prevents anemia and improves the energy and health of the whole family!',
@nyabongo updated.

2020-10-20 12:15 UTC, DevFojo approved these changes

2020-10-20 12:53 UTC, nyabongo approved these changes

2020-10-20 12:58 UTC, DevFojo approved these changes

2020-10-20 13:01 UTC, merged