Ser 228 limit nutrition training
one-acre-fund/ussd-sms pull request #165
Opened 2020-09-30 13:26 UTC by Bahatiroben

2020-10-21 13:36 UTC, nyabongo requested changes
Hey Robben I think you forgot to update the changelog.

2020-10-21 13:59 UTC, Bahatiroben commented
> Hey Robben I think you forgot to update the changelog.

Ohhh! I surely have forgot it. but have added it @nyabongo

2020-10-22 11:44 UTC, nyabongo requested changes
You seem to have 3 tests failing

2020-10-23 08:40 UTC, nyabongo requested changes

2020-10-23 08:40 UTC, nyabongo commented on CHANGELOG.md
> +### Added
the date  2020-10-22 and the added section is duplicated here.

2020-10-23 08:40 UTC, nyabongo commented on CHANGELOG.md
> +### Added
the date  2020-10-22 and the added section is duplicated here.

2020-10-23 08:43 UTC, Bahatiroben commented on CHANGELOG.md
> +### Added
@nyabongo sorry. I missed this. just changed to today's date.

2020-10-23 08:45 UTC, nyabongo approved these changes

2020-10-23 09:21 UTC, DevFojo approved these changes

2020-10-23 09:26 UTC, merged