add disable feature for training menu
one-acre-fund/ussd-sms pull request #207
Opened 2020-10-30 08:21 UTC by DevFojo

### Testing
Service: https://telerivet.com/p/0c6396c9/service/SVea040ce197886f68/edit

#### Steps
1. Enter account number
2. Enter 4 to select the "Training" option
3. Other training options should be hidden except Soil Training

2020-10-30 09:51 UTC, nyabongo requested changes
Shouldn't there be a changelog  update here? doesn't this also remove the maize recommendation or is that somewhere other than the the kenya-trainings-menu?

2020-10-30 09:57 UTC, DevFojo commented
> Shouldn't there be a changelog update here? doesn't this also remove the maize recommendation or is that somewhere other than the the kenya-trainings-menu?

Still working on it. Converting this PR to draft

2020-11-02 07:47 UTC, nyabongo approved these changes

2020-11-02 08:54 UTC, shejasabin approved these changes

2020-11-02 09:50 UTC, nyabongo approved these changes

2020-11-02 10:38 UTC, shejasabin approved these changes

2020-11-02 11:07 UTC, merged