remove redundant steps
one-acre-fund/ussd-sms pull request #227
Opened 2020-11-11 13:03 UTC by DevFojo

2020-11-12 09:42 UTC, nyabongo requested changes

2020-11-12 09:42 UTC, nyabongo commented on rw-legacy/core.js
> +const lang = 'en';
Shouldn't this be in Kinyarwanda primarily? maybe use a service variable to set it to english in development?

2020-11-13 12:20 UTC, nyabongo requested changes

2020-11-13 12:20 UTC, nyabongo commented on rw-legacy/core.js
> +    lang = 'en';
this might cause problems in the test service that is used for UAT, this should be kinyarwanda in that service.
Perhaps for development we can use a  service variable we sert at the service level so this line instead can be `lang = service.vars.lang || 'ki'`

2020-11-13 12:36 UTC, shejasabin commented on rw-legacy/lib/utils/message-translations.js
> +        'en': '1)Confirm order',
hey @DevFojo I have recently received a request to add this? did it change?

2020-11-13 12:51 UTC, DevFojo commented on rw-legacy/lib/utils/message-translations.js
> +        'en': '1)Confirm order',
Not very sure. I just followed the flow in the task

2020-11-17 15:30 UTC, closed without merging