Mob 80 jit columns
one-acre-fund/ussd-sms pull request #251
Opened 2020-12-02 15:41 UTC by Bahatiroben

2020-12-04 09:45 UTC, nyabongo requested changes
There should be tests that accompany these changes, the fact that you could make changes without any tests failing shows a gap in the tests. Please add tests.

2020-12-07 15:20 UTC, shejasabin submitted a review, later dismissed

2020-12-08 10:38 UTC, shejasabin approved these changes

2020-12-09 12:28 UTC, nyabongo approved these changes

2021-02-26 06:37 UTC, closed without merging