Consolidated Database v1
one-acre-fund/ussd-sms pull request #397
Opened 2021-08-10 08:03 UTC by ito-mobility

This pull request contains the following additions:

- Addition of Menu items
- Custom responses based on the sub-categories

2021-08-10 13:52 UTC, Bahatiroben requested changes

2021-08-10 13:52 UTC, Bahatiroben commented on ke-legacy/main.js
> -service.vars.current_enrollment_season_name = project.vars[env + '_current_enrollment_season']
@ito-mobility this line can not be removed or there might be some issues with enrollment and SHS. please keep the current implementation intact. since this file has no unit tests, its very hard for me to catch bugs. so, please remove a line when you are certain it won't break anything.

2021-08-11 06:29 UTC, ito-mobility commented on ke-legacy/main.js
> -service.vars.current_enrollment_season_name = project.vars[env + '_current_enrollment_season']
Sure Robben thanks for the reminder, we have only made changes to the staff menu. We will keep this in mind not to touch the other lines not related to the staff menu

2021-08-11 07:26 UTC, Bahatiroben requested changes

2021-08-11 07:26 UTC, Bahatiroben commented on ke-legacy/main.js
> -service.vars.current_enrollment_season_name = project.vars[env + '_current_enrollment_season']
@ito-mobility  can you check this exact line that I commented on? line 24 in ke-legacy/main.js that is definitely modified.

2021-08-11 08:12 UTC, Bahatiroben approved these changes

2021-08-11 08:13 UTC, merged