SHS client notification SER-15
one-acre-fund/ussd-sms pull request #77
Opened 2020-08-12 15:53 UTC by Bahatiroben

SER-15

As an SHS client, I want to receive a notification that lets me know when I can unlock my SHS, so that I can retrieve my unlock code via USSD

https://telerivet.com/p/0c6396c9/service/SV412b9240c4f8eea5/edit

- moving the kenya mobile money repayment receipt from telerivet to the repo
- sending notification once the user pays the loan in full

the current mock data on the service covers all of those cases and after simulating the service, you should receive 2 messages
1.  repayment notification
2. shs notification

2020-08-13 07:58 UTC, shejasabin commented on repayments/repayments.js
> +            to_number: contact.phone_number,
on the ticket, it says that you send this message to the phone number stored on Roster

2020-09-11 11:41 UTC, Bahatiroben commented on repayments/repayments.js
> +            to_number: contact.phone_number,
hey @shejasabin the above feedback is implemented

2020-09-11 13:21 UTC, nyabongo requested changes

2020-09-11 13:21 UTC, nyabongo commented on shared/rosterApi/getPhoneNumber.js
> +var logger = require('../../slack-logger/index');
Can you log this to Elk instead of slack `logger/elk/elk-logger.js` save slack for dev logs we expect to see once in a while

2020-09-11 16:17 UTC, nyabongo approved these changes

2020-09-14 06:48 UTC, shejasabin approved these changes

2020-09-14 06:55 UTC, merged