Record buyback transactions ser 170
one-acre-fund/ussd-sms pull request #85
Opened 2020-08-19 08:17 UTC by Bahatiroben

2020-08-20 12:35 UTC, nyabongo reviewed
Since this is tested and new, it is not legacy code, could you rename from mw_legacy to something else, even just malawi will do

2020-08-20 14:18 UTC, Bahatiroben commented
> Since this is tested and new, it is not legacy code, could you rename from mw_legacy to something else, even just malawi will do

implemented.

2020-08-20 14:36 UTC, nyabongo requested changes

2020-08-20 14:36 UTC, nyabongo commented on malawi/inputHandlers/inputHandlers.test.js
> +    });
this  test alone is not very useful, instead assert that the accountNumberInputHandler it exports is the same as the ` require('./accountNumberInputHandler');` e.g `expect(inputHandlers.accountNumberInputHandler).toBe( require('./accountNumberInputHandler'))`

2020-08-20 14:36 UTC, nyabongo commented on malawi/translations/index.js
> +        'en': 'Welcome to the OAF Malawi buyback portal. Please enter the account number of the client you are recording a transaction for.'
it might be worth using `en-mw` from the start here

2020-08-20 14:36 UTC, nyabongo commented on setupTests.js
> +global.main = jest.fn();
I don't think this is necessary, it is not a telerivet defined function, rather telerivet requires us to define it.

2020-08-24 05:48 UTC, shejasabin approved these changes

2020-08-24 06:42 UTC, merged