Record buyback 2 ser 170
one-acre-fund/ussd-sms pull request #90
Opened 2020-08-21 10:11 UTC by Bahatiroben

This is the secord part PR of the buyback transaction record.
first one is about setting up the structure for Malawi.
for this one, there is an implementation of actual buyback transaction record.

after the user is authenticated with their account number,

this handles the following:
- handling the selection of the crop to be sold
- handling the selection of the crop variety
- leaving the rest for the last(3rd) part PR of the task.

2020-08-24 09:33 UTC, nyabongo requested changes

2020-08-24 09:33 UTC, nyabongo commented on buyback-transactions/buyBackTransactions.js
> +    addInputHandler('crops', cropsInputHandler);
Avoid using string literals like this, instead, use a variable

2020-08-24 09:33 UTC, nyabongo commented on buyback-transactions/buyBackTransactions.js
> +    state.vars.crops = JSON.stringify({'1': 'Groundnuts', '2': 'Rice', '3': 'Pigeon peas'});
If these are constant, they are better set as a variable too, ideally outside the function since they don't change in the function

2020-08-24 09:33 UTC, nyabongo commented on buyback-transactions/inputHandlers/cropsInputHandler.js
> +        }
Could you convert lines 13-26 into  a standalone function, it makes for easier readability and is just generally better practice, it can be  function in the same file something like `var varieties = getVarietiesByCrop(crop)`

2020-08-24 09:33 UTC, nyabongo commented on malawi/inputHandlers/accountNumberInputHandler.test.js
> +        '3) Pigeon peas\n');
This is not testing what the function does. The function calls buybackTransactions.start()

2020-08-24 09:33 UTC, nyabongo commented on buyback-transactions/inputHandlers/varieties.test.js
> +
could you name this file to match the file it is testing

2020-08-26 13:30 UTC, nyabongo requested changes

2020-08-26 13:30 UTC, nyabongo commented on buyback-transactions/buybackTransactions.test.js
> +        expect(addInputHandler).toHaveBeenCalledWith('varieties', varietiesInputHandler.Handler);
please use the `cropsInputHandler.handlerName` and `varietiesInputHandler.handlerName` instead of the string literals here

2020-08-26 13:46 UTC, Bahatiroben commented on buyback-transactions/buybackTransactions.test.js
> +        expect(addInputHandler).toHaveBeenCalledWith('varieties', varietiesInputHandler.Handler);
Ohhh, thought it wasn't for tests too.

2020-08-26 15:13 UTC, Bahatiroben commented on buyback-transactions/buybackTransactions.test.js
> +        expect(addInputHandler).toHaveBeenCalledWith('varieties', varietiesInputHandler.Handler);
@nyabongo the feedback is implemented.

2020-08-26 15:17 UTC, nyabongo commented on buyback-transactions/buybackTransactions.test.js
> +        expect(addInputHandler).toHaveBeenCalledWith('varieties', varietiesInputHandler.Handler);
It makes the test explain what is going on better

2020-08-26 15:19 UTC, nyabongo approved these changes

2020-08-27 06:49 UTC, shejasabin approved these changes

2020-08-27 07:17 UTC, merged