Moving beyonic update code
one-acre-fund/ussd-sms pull request #93
Opened 2020-08-25 07:11 UTC by shejasabin

Moved the following service: https://telerivet.com/p/0c6396c9/service/SVe189af5831300300/edit from Telerivet to the codebase

Testing link: https://telerivet.com/p/0c6396c9/service/SV6e35fed0d513d236/edit

The service update columns in the default service table 'Client Portal 2.0' depending on the errors coming from Beyonic and sends the clients updates on the error.

2020-08-25 09:45 UTC, nyabongo requested changes

2020-08-25 09:45 UTC, nyabongo commented on setupTests.js
> +global.moment  = jest.fn();
moment probably shouldn't be mocked, treat it the same way as we treat underscore in line 2 above. install it using `npm i moment` then import it in this file and then assign it to the global.moment

2020-08-25 11:53 UTC, shejasabin commented on setupTests.js
> +global.moment  = jest.fn();
okay, did the change

2020-08-25 14:47 UTC, nyabongo approved these changes

2020-08-27 07:22 UTC, Bahatiroben approved these changes

2020-08-27 13:36 UTC, merged